name: Lighthouse

on: [pull_request]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Use Node.js 14.x (LTS)
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore Bundler cache
        uses: actions/cache@v2
        with:
          path: docs/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Configure Bundler cache
        run: |
          bundle config path vendor/bundle

      - name: Install dependencies
        run: |
          npm ci
          cd docs && bundle install && cd ..

      - name: Build docs
        run: npm run build:docs

      - name: Run Lighthouse CI
        run: npx lhci autorun
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
